### ISSUE TITLE
Проблема при запуске проекта с помощью gulp

### ISSUE THREAD

**Issue by mathetes** [vithar/bem.info#3]
После безошибочной установки запускаю проект с помощью gulp вылетает ошибка

 ~/allprojects/01_BEM/bem.info $ gulp
[09:03:06] Using gulpfile ~/allprojects/01_BEM/bem.info/gulpfile.js
[09:03:06] Starting 'watch'...
[09:03:06] Finished 'watch' after 15 ms
[09:03:06] Starting 'browser-sync'...
bs
[09:03:07] Finished 'browser-sync' after 48 ms
[09:03:07] Starting 'default'...
[09:03:07] 'default' errored after 482 ms
[09:03:07] Error: Cannot find module './desktop.bundles/index/index.bemtree.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Gulp.<anonymous> (/home/roman/allprojects/01_BEM/bem.info/gulpfile.js:31:17)
    at module.exports (/home/roman/allprojects/01_BEM/bem.info/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/roman/allprojects/01_BEM/bem.info/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/roman/allprojects/01_BEM/bem.info/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /home/roman/allprojects/01_BEM/bem.info/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/home/roman/allprojects/01_BEM/bem.info/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'desktop.bundles/index/index.min.css'
    at Error (native)

**Comment by vithar** [comment]
Fixed in this commit:
https://github.com/vithar/bem.info/commit/0b88b0779d0f45d71ff0cf2a9cde5be4f43e164c
